/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SearchDoc {
  id: string
  text: string
  date?: string
}
export interface SearchResult {
  id: string
  score: number
}
export interface Bm25Options {
  k1?: number
  b?: number
  halfLifeDays?: number
}
export interface TextAnalysis {
  length: number
  emojiCount: number
  casualScore: number
  formalScore: number
  hasQuestion: boolean
  hasList: boolean
  hasParagraphs: boolean
  sentenceCount: number
  structureScore: number
  addressing: string
}
export declare function analyzeText(text: string): TextAnalysis
export interface PostInput {
  id: string
  text: string
  date: string
  hasMedia: boolean
}
export interface PostAnalysis {
  id: string
  length: number
  category: string
  emojiCount: number
  casualScore: number
  formalScore: number
  structureScore: number
  hasQuestion: boolean
  hasList: boolean
  hasParagraphs: boolean
  sentenceCount: number
  addressing: string
  ctas: Array<string>
  products: Array<string>
}
export interface AnalysisReport {
  totalPosts: number
  avgLength: number
  medianLength: number
  mediaRate: number
  casualPct: number
  formalPct: number
  avgCasualScore: number
  avgStructureScore: number
  questionPct: number
  ctaPct: number
  postsPerWeek: number
  busiestDay: string
  posts: Array<PostAnalysis>
}
/** Batch analyze posts — full deep analysis natively */
export declare function analyzePosts(posts: Array<PostInput>): AnalysisReport
export interface ParsedPost {
  id: number
  date: string
  text: string
  hasMedia: boolean
  engagementScore: number
}
export interface HtmlParseResult {
  totalPosts: number
  posts: Array<ParsedPost>
}
/** Parse Telegram HTML export into structured data */
export declare function parseTelegramHtml(html: string): HtmlParseResult
/** Filter JSON array by field value (substring match) */
export declare function jsonFilter(jsonStr: string, field: string, value: string): string
/** Group JSON array by field, return counts */
export declare function jsonGroupBy(jsonStr: string, field: string): Array<Array<string>>
/** Convert CSV string to JSON string */
export declare function csvToJson(csvStr: string): string
/** Convert JSON array string to CSV string */
export declare function jsonToCsv(jsonStr: string): string
export type NativeBM25 = NativeBm25
export declare class NativeBm25 {
  constructor(options?: Bm25Options | undefined | null)
  addDocuments(docs: Array<SearchDoc>): void
  search(query: string, limit?: number | undefined | null): Array<SearchResult>
  clear(): void
  get size(): number
}
