sonar.projectKey=fr3shsmoke-ux_Podonki
sonar.organization=fr3shsmoke-ux
sonar.projectName=Podonki
sonar.sourceEncoding=UTF-8

sonar.sources=src,scripts,config
sonar.exclusions=data/**,docs/**,notebooks/**,.github/**,**/*.md,**/node_modules/**,**/*.min.js
sonar.coverage.exclusions=data/**,docs/**,notebooks/**,scripts/**,config/**,**/*.test.js,**/*.spec.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
