sonar.projectKey=fr3shsmoke-ux_Podonki
sonar.projectName=Podonki - Content Automation
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.spec.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.file.suffixes=.js,.jsx

sonar.coverage.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/.vscode/**,**/logs/**,**/coverage/**,**/Материалы/**,**/Проект\ Podonki/**
